---
version: "2.1"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    image: colorado-rla/server:dev
    depends_on:
      - postgresql
    ports:
      - "8888:8888"

  postgresql:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    image: colorado-rla/postgres:dev
    ports:
      - "5432:5432"

  httpd:
    build:
      context: .
      dockerfile: ./docker/httpd/Dockerfile
    image: colorado-rla/httpd:dev
    depends_on:
      - server
    links:
      - "server:backend"
    ports:
      - "8080:80"

  test-credentials:
    image: colorado-rla/postgres:dev
    command:
      - /bin/sh
      - -c
      - |
        until psql --single-transaction -v ON_ERROR_STOP=1 \
          -U corla -d corla -h postgresql \
          < /root/corla-test-credentials.psql; do
            sleep 5
        done
    depends_on:
      - postgresql
