---
version: "2.1"
services:
  server:
    image: quay.io/democracyworks/rla-server:latest
    depends_on:
      - postgresql
    ports:
      - "8888:8888"

  postgresql:
    image: quay.io/democracyworks/rla-postgres:latest
    ports:
      - "5432:5432"

  httpd:
    image: quay.io/democracyworks/rla-httpd:latest
    depends_on:
      - server
    links:
      - "server:backend"
    ports:
      - "8080:80"
